name: Dan Ross
favicon: null
layout_spectrum: 0.48235580138862133
typography_spectrum: 0.06115763075649738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6605020021088421
  lightness: 0.18633052078075707
  saturation: 0.9022319091018289
  rhythmicContrast: 0.3486943107564002
purpose: []
